#Random forest is based on the descision tree it shows the accuracy of given data set. Ensemble learning = ensemble learning means that dont predict the value by checking one of the dataset like- agar hum example lee A1,A2,A3 yha 3 log h or ye training data ke basis p output dere h, output m A1 ka output yes h or A2 ka no to hum final output yes nhi maan skte hume teeno ka output lena hoga or majority check krni hogi uske baad hume ek correct ans milega...
#Random password algo implementation.................. 

